baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Darshan Baral"
    description = "Website title"
    copyright = "aaa"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "First Last, Abbr."
		tagline = "Title"
		location = "City Name, ST"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "#"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "ai-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Tagline. Lorem ipsum dolor sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Job Title"
            dates = "2019 - *Present*"
            company = "Company Name"
            details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
        [[params.experience.list]]
            position = "Job Title"
            dates = "2018 - 2019"
            link = "#"
            company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "M.S. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "B.S. in Subject"
            college = "University of State-City"
            dates = "2004 - 2009"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Cooking"
        [[params.hobby.list]]		
		    hobby = "Hiking"
        [[params.hobby.list]]		
		    hobby = "Baking"